allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@eslint-react/ast@5.8.10'
  - '@eslint-react/core@5.8.10'
  - '@eslint-react/eslint-plugin@5.8.10'
  - '@eslint-react/eslint@5.8.10'
  - '@eslint-react/jsx@5.8.10'
  - '@eslint-react/shared@5.8.10'
  - '@eslint-react/var@5.8.10'
  - '@next/env@16.2.7'
  - '@next/swc-darwin-arm64@16.2.7'
  - '@next/swc-darwin-x64@16.2.7'
  - '@next/swc-linux-arm64-gnu@16.2.7'
  - '@next/swc-linux-arm64-musl@16.2.7'
  - '@next/swc-linux-x64-gnu@16.2.7'
  - '@next/swc-linux-x64-musl@16.2.7'
  - '@next/swc-win32-arm64-msvc@16.2.7'
  - '@next/swc-win32-x64-msvc@16.2.7'
  - '@typescript-eslint/eslint-plugin@8.60.1'
  - '@typescript-eslint/parser@8.60.1'
  - '@typescript-eslint/project-service@8.60.1'
  - '@typescript-eslint/scope-manager@8.60.1'
  - '@typescript-eslint/tsconfig-utils@8.60.1'
  - '@typescript-eslint/type-utils@8.60.1'
  - '@typescript-eslint/types@8.60.1'
  - '@typescript-eslint/typescript-estree@8.60.1'
  - '@typescript-eslint/utils@8.60.1'
  - '@typescript-eslint/visitor-keys@8.60.1'
  - eslint-plugin-react-dom@5.8.10
  - eslint-plugin-react-jsx@5.8.10
  - eslint-plugin-react-naming-convention@5.8.10
  - eslint-plugin-react-rsc@5.8.10
  - eslint-plugin-react-web-api@5.8.10
  - eslint-plugin-react-x@5.8.10
  - graphql@16.14.1
  - next@16.2.7
  - typescript-eslint@8.60.1
